language: r

cache: packages

env:
  global:
    - secure: "heZ/ZzYobj+Ypfc1dZbc4k5nni+fv8EBVfYTC3NBgpbtqWksV6RbCle1LTUz6QF+uQBIpzOum8aozzdLd3UGqQEAMIUmmSzHX2tOEIR7OWkHT7Hp8viA07PWt9HaUpBuJRb8bYrCIsQMpH6jtXT2iHkXO4ODo+gZvkGN57F02zfk3fPeZXwr6N76glrbIXylIhMb2hV6Ziwq7EamnWHYWBqR2QOAmy3PjD+8q6AWmR8b9ZU70npm8LxcJLyTVHrSocTfQM5yQV2xoHYynHBRq7bBA7pJwv0cmZNeVvSlJkakhsApcFZG7mYIeTLs4PXPLVHpRBNC+UMs87iQXJWMyecmC8ysZSmYbpGmXDSRcO33Z4pYiW83g6twYrXvz/WDWeU+VruUDvn4VVHiqGrayW1vCuC/i5xiPJ4OkLz31kwHjK0e/+EqjRXal+Pz9Sk6R1yzsGugN2RBfkX9k4l3eZoMMiaFpY9dG4Izb+iRwiSLEB8V9/qxxOngWsrqjrjkzdonPsty9VINCT1OpmCmZXG0J3xCb+H30+ykhj5g9z9N65oHcbLj7nTx2sxFVRPL7Ob2OtWV5B/wWpURxEpyZRL1KKJXZvq5mZJDXucFKHXe2zwBix6CZ1/nu+7XqqcrA/G3hWSfDRMzGbglWMFW+aMXpR103PQZNDu3T4u4OlE="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
